version: "3.8"

# Variables used in this Compose file are handled via Portainer, hence a different syntax from base infra
services:
    mongodb:
        image: mongo:6.0.4
        container_name: quizae-mongodb
        command: --replSet rs0 --keyFile /data/mongo-replica.key --bind_ip_all
        volumes:
            - mongo_data:/data/db
            - ./config/mongo/file.key:/data/mongo-replica.key
        networks:
            - db_access
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
            MONGO_INITDB_DATABASE: $MONGO_DATABASE

    backend:
        image: ghcr.io/mareddie/quizae-backend:latest
        networks:
            - db_access
            - public
        environment:
            APP_ENV: $APP_ENV
            DATABASE_URL: $APP_DATABASE_URL
            JWT_SECRET: $APP_JWT_SECRET
        labels:
            - traefik.enable=true
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.routers.backend.rule=Host(`$QUIZAE_BACKEND_HOST`)
            - traefik.http.routers.backend.tls=true
            - traefik.http.routers.backend.tls.certresolver=default-resolver
            - traefik.http.routers.backend.service=backend
            - traefik.http.services.backend.loadbalancer.server.port=3000

networks:
    db_access:
        external: true
    public:
        external: true

volumes:
    mongo_data:
        external: true
