version: "3.8"

services:
    mongodb:
        image: mongo:6.0.4
        volumes:
            - mongo_data:/data/db
        networks:
            - db_access
        environment:
            MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongoRootUsername
            MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongoRootPassword
            MONGO_INITDB_DATABASE: /run/secrets/mongoDefaultDatabase
        secrets:
            - mongoRootUsername
            - mongoRootPassword
            - mongoDefaultDatabase

    backend:
        image: ghcr.io/mareddie/quizae-backend:latest
        networks:
            - db_access
            - public
        environment:
            APP_ENV: $APP_ENV
            DATABASE_URL: $APP_DATABASE_URL
            JWT_SECRET: $APP_JWT_SECRET
        deploy:
            labels:
                - traefik.enable=true
                - traefik.http.routers.backend.entrypoints=websecure
                - traefik.http.routers.backend.rule=Host(`api.quizae.wtf`)
                - traefik.http.routers.backend.tls=true

networks:
    db_access:
        external: true
    public:
        external: true

volumes:
    mongo_data:
        external: true

secrets:
    mongoRootUsername:
        external: true
    mongoRootPassword:
        external: true
    mongoDefaultDatabase:
        external: true
