# TODO: migrate to docker instead of Swarm
version: "3.8"

services:
    mongodb:
        image: mongo:6.0.4
        volumes:
            - mongo_data:/data/db
        networks:
            - db_access
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
            MONGO_INITDB_DATABASE: $MONGO_DATABASE

    backend:
        image: ghcr.io/mareddie/quizae-backend:latest
        networks:
            - db_access
            - public
        environment:
            APP_ENV: $APP_ENV
            DATABASE_URL: $APP_DATABASE_URL
            JWT_SECRET: $APP_JWT_SECRET
        deploy:
            labels:
                - traefik.enable=true
                - traefik.http.routers.backend.entrypoints=websecure
                - traefik.http.routers.backend.rule=Host(`api.quizae.com`)
                - traefik.http.routers.backend.tls=true
                - traefik.http.routers.backend.tls.certresolver=default-resolver
                - traefik.http.routers.backend.service=backend
                - traefik.http.services.backend.loadbalancer.server.port=3000

networks:
    db_access:
        external: true
    public:
        external: true

volumes:
    mongo_data:
        external: true
